### PR TITLE
Fix serialization of domain with superclass

### PR DESCRIPTION
**Pull request by slestang**
Contains corresponding tests.

I don't know if testing if _field_ is _null_ and throw a NoSuchFieldException is the correct way of doing things.

### CODE REVIEW

**Comment by kaerfredoc** [comment]
Hi Rob. Any way to get this pull request merged? Saw there was a problem with the build, not sure about the status.

**Comment by robfletcher** [comment]
I have basically the same change in master already just without the null check. Trying to figure out what the problem is with the Travis build but it's taking forever to load up.

**Comment by robfletcher** [comment]
Looks like the change causes the unit tests to fail as the `id` field is synthetic & not found by `ReflectionUtils`

**Comment by robfletcher** [comment]
All merged in, thanks.

**Pull request merged**
